<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        Label:
            id: click_label
            text: "pick 123"
            font_size: 32
        Spinner:
            id:spinner_id
            text:"yesss"
            values: ["J", "E", "S", "U", "S"]

            on_text: root.spinner_clicked(spinner_id.text)

        Label:
            text: ''